### ISSUE TITLE
Error during build (zxing/ngx-scanner 3.0.0 and angular 8.2.14) in Docker Compose

### ISSUE THREAD

**Issue by sudhakar-sekar** [zxing-js/ngx-scanner#328]
**Describe the bug**
While running angular application in docker compose (ng serve) errors:

>  | ERROR in ../node_modules/@zxing/ngx-scanner/lib/browser-multi-format-continuous-reader.d.ts:12:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 12     get isTorchAvailable(): Observable<boolean>;
|            ~~~~~~~~~~~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:104:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 104     get codeReader(): BrowserMultiFormatContinuousReader;
|             ~~~~~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:108:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 108     set device(device: MediaDeviceInfo | null);
|             ~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:116:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 116     get device(): MediaDeviceInfo | null;
|             ~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:120:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 120     get formats(): BarcodeFormat[];
|             ~~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:126:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 126     set formats(input: BarcodeFormat[]);
|             ~~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:130:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 130     get hints(): Map<DecodeHintType, any>;
|             ~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:134:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 134     set hints(hints: Map<DecodeHintType, any>);
|             ~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:138:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 138     set isAutostarting(state: boolean | null);
|             ~~~~~~~~~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:142:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 142     get isAutostarting(): boolean | null;
|             ~~~~~~~~~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:146:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 146     set torch(on: boolean);
|             ~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:150:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 150     set enable(enabled: boolean);
|             ~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:154:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 154     get enabled(): boolean;
|             ~~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:158:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 158     get tryHarder(): boolean;
|             ~~~~~~~~~
| ../node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts:162:9 - error TS1086: An accessor cannot be declared in an ambient context.
|
| 162     set tryHarder(enable: boolean);
|             ~~~~~~~~~
|
| ** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
| ℹ ｢wdm｣: Failed to compile.

Package version details:

> "@angular/animations": "^8.2.14",
        "@angular/cdk": "^8.2.3",
        "@angular/common": "^8.2.14",
        "@angular/compiler": "^8.2.14",
        "@angular/core": "^8.2.14",
        "@angular/flex-layout": "^7.0.0-beta.23",
        "@angular/forms": "^8.2.14",
        "@angular/material": "^7.3.2",
        "@angular/platform-browser": "^8.2.14",
        "@angular/platform-browser-dynamic": "^8.2.14",
        "@angular/router": "^8.2.14",
       "@zxing/library": "0.16.0",
       "@zxing/ngx-scanner": "3.0.0"

I found some solutions to add skipLibCheck in tsconfig.json, I don't want to skip lib check.

`"angularCompilerOptions": {
    "skipLibCheck": true
  }`

Anyone help me to resolve this issue ASAP.

Thanks in advance.

**Comment by sudhakar-sekar** [comment]
When trying to enable PWA, I missed some configurations, I am able to find the issue and fixed. Also tested out.
Also missed some configurations in docker file and found it. Now, its working as i expected.
The issue is not because of this package.
Thanks for everyone who have spend time to find the issue root cause.

**Comment by tolyaganzin** [comment]
on ng serve 
```
ERROR in node_modules/@zxing/ngx-scanner/lib/browser-multi-format-continuous-reader.d.ts(12,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(104,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(108,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(116,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(120,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(126,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(130,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(134,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(138,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(142,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(146,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(150,9): error TS1086: An accessor cannot be declared in an ambient context.

node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(154,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(158,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@zxing/ngx-scanner/lib/zxing-scanner.component.d.ts(162,9): error TS1086: An accessor cannot be declared in an ambient context.
```

package version : 
```
  "@angular/animations": "7.2.12",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "7.2.12",
    "@angular/compiler": "7.2.12",
    "@angular/compiler-cli": "7.2.12",
    "@angular/core": "7.2.12",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "7.2.12",
    "@angular/http": "7.2.12",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "7.2.12",
    "@angular/platform-browser-dynamic": "7.2.12",
    "@angular/platform-server": "7.2.12",
    "@angular/router": "7.2.12",
    "@angular/service-worker": "7.2.12",
    "@zxing/ngx-scanner": "^3.0.1",
```

**Comment by sudhakar-sekar** [comment]
@tolyaganzin are you using it in docker or docker-compose?
what's the typescript version?

**Comment by martea** [comment]
@tolyaganzin did you find a solution, same problem after upgrading to 3.0.1
